---
title: "Kaggle Copy"
author: "Siyu Zhu"
date: "9/18/2018"
output:
  pdf_document: default
  html_document:
    df_print: paged
---





perchase tendency
```{r}
count_purchase_hm <- function(data_subset){
  pattern = "(buy)|(purchase)"
  corpus_purchase_selection <- sapply(data_subset$cleaned_hm, grep, pattern = pattern)
  v = c()
  for (i in 1:length(corpus_purchase_selection)){
    test = (as.numeric(corpus_purchase_selection[i] == 1) != 1)
    if(is.na(test)){
      
    }
    else{
      v = c(v, i)
    }
  }
  return(v)
}

vector <- count_purchase_hm(subset(hmdemo_data, marital == "married"))
length(vector)
vector <- count_purchase_hm(hmdemo_data)
length(vector)


```






```{r}
library(text2vec)
library(magrittr)
```

```{r}
prep_fun = tolower
tok_fun = word_tokenizer
hmdemo_data <- read.csv("hm_data_withdemo.csv", stringsAsFactors = F)
it_train = itoken(hmdemo_data$cleaned_hm, 
             preprocessor = prep_fun, 
             tokenizer = tok_fun, 
             ids = hmdemo_data$hmid, 
             progressbar = TRUE)
vocab = create_vocabulary(it_train)

vectorizer = vocab_vectorizer(vocab)
t1 = Sys.time()
dtm_train = create_dtm(it_train, vectorizer)
print(difftime(Sys.time(), t1, units = 'sec'))

dim(dtm_train)

# identical(as.numeric(rownames(dtm_train)), hm_data$hmid)
table(as.numeric(rownames(dtm_train)) - hmdemo_data$hmid)
```


```{r}
library(glmnet)
NFOLDS = 4
t1 = Sys.time()
glmnet_classifier = cv.glmnet(x = dtm_train, y = hmdemo_data$gender, 
                              family = 'binomial', 
                              # L1 penalty
                              alpha = 1,
                              # interested in the area under ROC curve
                              type.measure = "auc",
                              # 5-fold cross-validation
                              nfolds = NFOLDS,
                              # high value is less accurate, but has faster training
                              thresh = 1e-3,
                              # again lower number of iterations for faster training
                              maxit = 1e3)
print(difftime(Sys.time(), t1, units = 'sec'))
```


```{r}
plot(glmnet_classifier)
```

```{r}
print(paste("max AUC =", round(max(glmnet_classifier$cvm), 4)))
```
```{r}
library(reticulate)
use_python("~/anaconda3/bin/python")
```

```{python}
import pandas as pd

```


